AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    EC2SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "launch-wizard-1 created 2022-10-05T22:33:20.997Z"
            GroupName: "launch-wizard-1"
            VpcId: !GetAtt EC2Subnet.VpcId
            SecurityGroupIngress: 
              - 
                SourceSecurityGroupId: !Ref EC2SecurityGroup2
                SourceSecurityGroupOwnerId: !Ref AWS::AccountId
                FromPort: 22
                IpProtocol: "tcp"
                ToPort: 22
              - 
                SourceSecurityGroupId: !Ref EC2SecurityGroup2
                SourceSecurityGroupOwnerId: !Ref AWS::AccountId
                FromPort: -1
                IpProtocol: "icmp"
                ToPort: -1
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"

    EC2SecurityGroup2:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "holpubSG"
            GroupName: "holpubSG"
            VpcId: !GetAtt EC2Subnet.VpcId
            SecurityGroupIngress: 
              - 
                CidrIp: "73.119.61.0/32"
                FromPort: 22
                IpProtocol: "tcp"
                ToPort: 22
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"

    EC2Subnet:
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !GetAtt EC2Instance2.AvailabilityZone
            CidrBlock: "10.0.2.0/24"
            VpcId: !GetAtt EC2Subnet2.VpcId
            MapPublicIpOnLaunch: true
            Tags: 
              - 
                Key: "Name"
                Value: "sn-private-b"

    EC2Subnet2:
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
            CidrBlock: "10.0.1.0/24"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: false
            Tags: 
              - 
                Key: "Name"
                Value: "sn-public-a"

    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-026b57f3c383c2eec"
            InstanceType: "t3.micro"
            KeyName: "vpcpubhol"
            AvailabilityZone: !Sub "${AWS::Region}a"
            Tenancy: "default"
            SubnetId: "subnet-07878c858d861a6e6"
            EbsOptimized: true
            SecurityGroupIds: 
              - "sg-04de674512e8d003d"
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/xvda"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 8
                    SnapshotId: "snap-07bb85133b158fe99"
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            Tags: 
              - 
                Key: "Name"
                Value: "hol-pub-instance"
            HibernationOptions: 
                Configured: false
            CpuOptions: 
                CoreCount: 1
                ThreadsPerCore: 2
            EnclaveOptions: 
                Enabled: false

    EC2Instance2:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-026b57f3c383c2eec"
            InstanceType: "t3.micro"
            KeyName: "vpcprivhol"
            AvailabilityZone: !Sub "${AWS::Region}b"
            Tenancy: "default"
            SubnetId: "subnet-00b1588160c53ab5f"
            EbsOptimized: true
            SecurityGroupIds: 
              - "sg-09a0333d807ef868c"
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/xvda"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 8
                    SnapshotId: "snap-07bb85133b158fe99"
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            Tags: 
              - 
                Key: "Name"
                Value: "hol-priv-instance"
            HibernationOptions: 
                Configured: false
            CpuOptions: 
                CoreCount: 1
                ThreadsPerCore: 2
            EnclaveOptions: 
                Enabled: false

    EC2VolumeAttachment:
        Type: "AWS::EC2::VolumeAttachment"
        Properties:
            VolumeId: "vol-0f073a71c52000ba6"
            InstanceId: !Ref EC2Instance2
            Device: "/dev/xvda"

    EC2VolumeAttachment2:
        Type: "AWS::EC2::VolumeAttachment"
        Properties:
            VolumeId: "vol-077e54bd6b823e7b1"
            InstanceId: !Ref EC2Instance
            Device: "/dev/xvda"

    EC2NetworkInterfaceAttachment:
        Type: "AWS::EC2::NetworkInterfaceAttachment"
        Properties:
            NetworkInterfaceId: "eni-0614099dffae7d8b6"
            DeviceIndex: 0
            InstanceId: !Ref EC2Instance
            DeleteOnTermination: true

    EC2NetworkInterfaceAttachment2:
        Type: "AWS::EC2::NetworkInterfaceAttachment"
        Properties:
            NetworkInterfaceId: "eni-0826abb7835969e16"
            DeviceIndex: 0
            InstanceId: !Ref EC2Instance2
            DeleteOnTermination: true

    EC2VPC:
        Type: "AWS::EC2::VPC"
        Properties:
            CidrBlock: "10.0.0.0/16"
            EnableDnsSupport: true
            EnableDnsHostnames: false
            InstanceTenancy: "default"
            Tags: 
              - 
                Key: "Name"
                Value: "HoLVPC"

    EC2VPCGatewayAttachment:
        Type: "AWS::EC2::VPCGatewayAttachment"
        Properties:
            InternetGatewayId: "igw-07a5ac9bb16cf3f16"
            VpcId: !GetAtt EC2Subnet.VpcId

